import { DocumentAnalysisResult, SummaryData } from "@/types";
import { jsPDF } from "jspdf";

/**
 * Copies plain or formatted text to system clipboard.
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator?.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    const textArea = document.createElement("textarea");
    textArea.value = text;
    textArea.style.position = "fixed";
    textArea.style.left = "-999999px";
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand("copy");
    document.body.removeChild(textArea);
    return successful;
  } catch (err) {
    console.error("Clipboard copy error:", err);
    return false;
  }
}

/**
 * Downloads a string or blob as a named file in the browser.
 */
export function downloadFile(content: string, filename: string, mimeType: string = "text/plain;charset=utf-8") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generates a clean Markdown export representation.
 */
export function generateMarkdownExport(summary: SummaryData, docTitle: string): string {
  const lines: string[] = [
    `# Executive Summary: ${docTitle}`,
    `*Generated by Unthinkable Document Summary Assistant | Length: ${summary.length.toUpperCase()} | Format: ${summary.format.toUpperCase()}*`,
    ``,
    `---`,
    ``,
    `## 📌 Overview`,
    `${summary.overview}`,
    ``,
    `## 🎯 Key Takeaways`,
    ...summary.keyTakeaways.map((t) => `- ${t}`),
    ``,
  ];

  if (summary.sections && summary.sections.length > 0) {
    lines.push(`## 📑 Core Thematic Breakdown`);
    for (const sec of summary.sections) {
      lines.push(`### ${sec.title}`);
      lines.push(`${sec.content}`);
      if (sec.bullets && sec.bullets.length > 0) {
        lines.push(``);
        lines.push(...sec.bullets.map((b) => `  * ${b}`));
      }
      lines.push(``);
    }
  }

  if (summary.entities) {
    lines.push(`## 📊 Critical Entities & Deadlines`);
    if (summary.entities.datesAndDeadlines.length > 0) {
      lines.push(`- **Dates & Deadlines**: ${summary.entities.datesAndDeadlines.join(", ")}`);
    }
    if (summary.entities.metricsAndNumbers.length > 0) {
      lines.push(`- **Key Metrics & Figures**: ${summary.entities.metricsAndNumbers.join(", ")}`);
    }
    if (summary.entities.actionItems.length > 0) {
      lines.push(`- **High-Priority Actions**:`);
      lines.push(...summary.entities.actionItems.map((a) => `  * ${a}`));
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated on ${new Date().toLocaleDateString()} at ${summary.generatedAt} via Unthinkable Solutions Document Intelligence*`);

  return lines.join("\n");
}

/**
 * Generates and downloads an Unthinkable-styled executive PDF report.
 */
export function exportToPdf(summary: SummaryData, docTitle: string) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const margin = 20;
  const pageWidth = 210;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = 24;

  // Header branding bar
  doc.setFillColor(11, 15, 23); // Obsidian #0b0f17
  doc.rect(0, 0, pageWidth, 20, "F");

  doc.setFillColor(93, 214, 103); // Unthinkable Green #5dd667
  doc.rect(0, 19, pageWidth, 1.5, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("UNTHINKABLE SOLUTIONS", margin, 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("DOCUMENT INTELLIGENCE ASSISTANT", pageWidth - margin, 12, { align: "right" });

  yPos = 32;

  // Document Title
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  const splitTitle = doc.splitTextToSize(docTitle, contentWidth);
  doc.text(splitTitle, margin, yPos);
  yPos += (splitTitle.length * 7) + 2;

  // Metadata Pill
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  doc.text(`Length: ${summary.length.toUpperCase()} | Format: ${summary.format.toUpperCase()} | Words: ~${summary.wordCount} | Generated: ${new Date().toLocaleDateString()}`, margin, yPos);
  yPos += 8;

  // Horizontal Rule
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  // Section 1: Executive Overview
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("1. Executive Overview", margin, yPos);
  yPos += 6;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  const splitOverview = doc.splitTextToSize(summary.overview, contentWidth);
  doc.text(splitOverview, margin, yPos);
  yPos += (splitOverview.length * 5.2) + 8;

  // Section 2: Key Takeaways
  if (yPos > 240) {
    doc.addPage();
    yPos = 24;
  }

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("2. Key Takeaways & Core Insights", margin, yPos);
  yPos += 6;

  doc.setFontSize(9.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);

  for (const takeaway of summary.keyTakeaways) {
    if (yPos > 260) {
      doc.addPage();
      yPos = 24;
    }
    // Bullet dot
    doc.setFillColor(93, 214, 103);
    doc.circle(margin + 2, yPos - 1.2, 1, "F");
    
    const splitT = doc.splitTextToSize(takeaway, contentWidth - 8);
    doc.text(splitT, margin + 7, yPos);
    yPos += (splitT.length * 5) + 3;
  }

  yPos += 4;

  // Section 3: Sections
  if (summary.sections && summary.sections.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 24;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("3. Detailed Structural Breakdown", margin, yPos);
    yPos += 6;

    for (const sec of summary.sections) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 24;
      }

      doc.setFontSize(10.5);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 41, 59);
      doc.text(`• ${sec.title}`, margin, yPos);
      yPos += 5;

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(71, 85, 105);
      const splitSec = doc.splitTextToSize(sec.content, contentWidth - 4);
      doc.text(splitSec, margin + 4, yPos);
      yPos += (splitSec.length * 4.8) + 4;
    }
  }

  // Footer on all pages
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Page ${i} of ${pageCount} — Confidential Summary Report`, pageWidth / 2, 290, { align: "center" });
  }

  const safeFilename = docTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase().slice(0, 35);
  doc.save(`${safeFilename}_executive_summary.pdf`);
}
