"use client";

import React, { useState } from "react";
import { X, Download, FileText, FileCode, Check, Copy, Sparkles, BookCheck } from "lucide-react";
import { DocumentAnalysisResult, SummaryLength } from "@/types";
import { copyToClipboard, downloadFile, exportToPdf, generateMarkdownExport } from "@/lib/export-utils";

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  documentTitle: string;
  analysis: DocumentAnalysisResult;
  activeLength: SummaryLength;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  documentTitle,
  analysis,
  activeLength,
}) => {
  const [copied, setCopied] = useState<string | null>(null);

  if (!isOpen) return null;

  const currentSummary = analysis.summaries[activeLength] || analysis.summaries.medium;

  const handleExportPdf = () => {
    exportToPdf(currentSummary, documentTitle);
    onClose();
  };

  const handleExportMarkdown = () => {
    const md = generateMarkdownExport(currentSummary, documentTitle);
    const safeName = documentTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase();
    downloadFile(md, `${safeName}_summary.md`, "text/markdown;charset=utf-8");
    onClose();
  };

  const handleExportJson = () => {
    const jsonStr = JSON.stringify(
      {
        documentTitle,
        exportTimestamp: new Date().toISOString(),
        summary: currentSummary,
        readability: analysis.readability,
        suggestions: analysis.suggestions,
        extractedMetadata: {
          wordCount: analysis.extracted.wordCount,
          charCount: analysis.extracted.charCount,
          estimatedReadingMinutes: analysis.extracted.estimatedReadingMinutes,
        },
      },
      null,
      2
    );
    const safeName = documentTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase();
    downloadFile(jsonStr, `${safeName}_analysis.json`, "application/json;charset=utf-8");
    onClose();
  };

  const handleExportTxt = () => {
    const txt = `${documentTitle.toUpperCase()} - SUMMARY REPORT\nGenerated by Unthinkable Document Assistant\n\nOVERVIEW:\n${currentSummary.overview}\n\nKEY TAKEAWAYS:\n${currentSummary.keyTakeaways.map((t) => `• ${t}`).join("\n")}\n\nACTION ITEMS:\n${currentSummary.entities.actionItems.map((a) => `[ ] ${a}`).join("\n")}`;
    const safeName = documentTitle.replace(/[^a-z0-9]/gi, "_").toLowerCase();
    downloadFile(txt, `${safeName}_summary.txt`);
    onClose();
  };

  const handleCopyMarkdown = async () => {
    const md = generateMarkdownExport(currentSummary, documentTitle);
    const success = await copyToClipboard(md);
    if (success) {
      setCopied("md");
      setTimeout(() => setCopied(null), 2000);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-white dark:bg-unthinkable-panel border border-slate-200 dark:border-unthinkable-border rounded-2xl max-w-lg w-full p-6 sm:p-8 shadow-2xl relative">
        
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-5 right-5 p-1.5 rounded-lg text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-unthinkable-card transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center space-x-3 mb-2">
          <div className="w-10 h-10 rounded-xl bg-[#5dd667]/20 border border-[#5dd667]/30 flex items-center justify-center text-[#2d7534] dark:text-[#5dd667]">
            <Download className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-slate-900 dark:text-white">
              Export Document Intelligence
            </h3>
            <p className="text-xs text-slate-500 dark:text-unthinkable-textMuted">
              Choose your preferred report format.
            </p>
          </div>
        </div>

        {/* Options Grid */}
        <div className="mt-6 space-y-3">
          
          {/* PDF */}
          <div
            onClick={handleExportPdf}
            className="p-4 rounded-xl border border-slate-200 dark:border-unthinkable-border hover:border-[#5dd667]/60 bg-slate-50/50 dark:bg-unthinkable-card/40 hover:bg-slate-50 dark:hover:bg-unthinkable-card cursor-pointer transition-all flex items-center justify-between group"
          >
            <div className="flex items-center space-x-3">
              <div className="w-9 h-9 rounded-lg bg-red-100 dark:bg-red-950/40 text-red-600 dark:text-red-400 flex items-center justify-center font-bold text-xs">
                PDF
              </div>
              <div>
                <h4 className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-[#5dd667] transition-colors">
                  Branded Executive PDF
                </h4>
                <p className="text-xs text-slate-500 dark:text-unthinkable-textMuted">
                  Styled with Unthinkable colors, headers, and key takeaways.
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-400 group-hover:text-[#5dd667] transition-colors" />
          </div>

          {/* Markdown */}
          <div
            onClick={handleExportMarkdown}
            className="p-4 rounded-xl border border-slate-200 dark:border-unthinkable-border hover:border-[#5dd667]/60 bg-slate-50/50 dark:bg-unthinkable-card/40 hover:bg-slate-50 dark:hover:bg-unthinkable-card cursor-pointer transition-all flex items-center justify-between group"
          >
            <div className="flex items-center space-x-3">
              <div className="w-9 h-9 rounded-lg bg-blue-100 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400 flex items-center justify-center font-bold text-xs">
                MD
              </div>
              <div>
                <h4 className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-[#5dd667] transition-colors">
                  Markdown Document (.md)
                </h4>
                <p className="text-xs text-slate-500 dark:text-unthinkable-textMuted">
                  Structured markdown with checklists and entities.
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-400 group-hover:text-[#5dd667] transition-colors" />
          </div>

          {/* JSON */}
          <div
            onClick={handleExportJson}
            className="p-4 rounded-xl border border-slate-200 dark:border-unthinkable-border hover:border-[#5dd667]/60 bg-slate-50/50 dark:bg-unthinkable-card/40 hover:bg-slate-50 dark:hover:bg-unthinkable-card cursor-pointer transition-all flex items-center justify-between group"
          >
            <div className="flex items-center space-x-3">
              <div className="w-9 h-9 rounded-lg bg-emerald-100 dark:bg-emerald-950/40 text-[#2d7534] dark:text-[#5dd667] flex items-center justify-center font-bold text-xs">
                JSON
              </div>
              <div>
                <h4 className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-[#5dd667] transition-colors">
                  Raw Structured Data (.json)
                </h4>
                <p className="text-xs text-slate-500 dark:text-unthinkable-textMuted">
                  Complete analysis, readability scores, and suggestions payload.
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-400 group-hover:text-[#5dd667] transition-colors" />
          </div>

          {/* TXT */}
          <div
            onClick={handleExportTxt}
            className="p-4 rounded-xl border border-slate-200 dark:border-unthinkable-border hover:border-[#5dd667]/60 bg-slate-50/50 dark:bg-unthinkable-card/40 hover:bg-slate-50 dark:hover:bg-unthinkable-card cursor-pointer transition-all flex items-center justify-between group"
          >
            <div className="flex items-center space-x-3">
              <div className="w-9 h-9 rounded-lg bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-300 flex items-center justify-center font-bold text-xs">
                TXT
              </div>
              <div>
                <h4 className="text-sm font-bold text-slate-900 dark:text-white group-hover:text-[#5dd667] transition-colors">
                  Plain Text Summary (.txt)
                </h4>
                <p className="text-xs text-slate-500 dark:text-unthinkable-textMuted">
                  Clean text format for quick notes and email memos.
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-400 group-hover:text-[#5dd667] transition-colors" />
          </div>

        </div>

        {/* Quick Clipboard Action */}
        <div className="mt-6 pt-4 border-t border-slate-100 dark:border-unthinkable-border flex items-center justify-between">
          <span className="text-xs text-slate-500 dark:text-unthinkable-textMuted">
            Or copy directly to clipboard:
          </span>
          <button
            onClick={handleCopyMarkdown}
            className="px-3 py-1.5 rounded-lg bg-slate-100 dark:bg-unthinkable-card text-slate-700 dark:text-slate-300 text-xs font-semibold hover:text-slate-900 dark:hover:text-white flex items-center gap-1.5 transition-colors"
          >
            {copied === "md" ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied === "md" ? "Copied Markdown!" : "Copy as Markdown"}</span>
          </button>
        </div>

      </div>
    </div>
  );
};
